[supervisord]
nodaemon=true

[program:php-fpm]
command=/usr/local/sbin/php-fpm

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"

[program:ssr]
directory=/var/www
command=php artisan inertia:start-ssr
autostart=true
autorestart=true
stdout_logfile=/var/log/ssr.log
stderr_logfile=/var/log/ssr.err.log
