/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
    interface RouteList {
        dashboard: [];
        'profile.edit': [];
        'profile.update': [];
        'profile.destroy': [];
        'password.edit': [];
        'password.update': [];
        appearance: [];
        register: [];
        login: [];
        'password.request': [];
        'password.email': [];
        'password.reset': [
            {
                name: 'token';
                required: true;
            },
        ];
        'password.store': [];
        'verification.notice': [];
        'verification.verify': [
            {
                name: 'id';
                required: true;
            },
            {
                name: 'hash';
                required: true;
            },
        ];
        'verification.send': [];
        'password.confirm': [];
        logout: [];
        'sites.index': [];
        'sites.update': [
            {
                name: 'site';
                required: true;
                binding: 'id';
            },
        ];
        'sites.destroy': [
            {
                name: 'site';
                required: true;
                binding: 'id';
            },
        ];
        'sites.store': [];
        'speed-dial': [];
        home: [];
        'storage.local': [
            {
                name: 'path';
                required: true;
            },
        ];
    }
}
export {};
