name: linter

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

permissions:
  contents: write

jobs:
  composer-lint:
    name: Composer lint
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ '8.4', '8.5' ]
    steps:
      - uses: actions/checkout@v6
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm ci
      - name: Composer lint check
        run: composer run lint:check
  
  composer-test:
    name: Composer test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version: [ '8.4', '8.5' ]
    steps:
      - uses: actions/checkout@v6
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
      - name: Install Dependencies
        run: |
          composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
          npm ci
      - name: Composer test
        run: composer run test

  npm-format-check:
    name: Npm format:check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Dependencies
        run: npm ci
      - name: npm format:check
        run: npm run format:check

  npm-lint-check:
    name: npm lint:check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install Dependencies
        run: npm ci
      - name: npm format:check
        run: npm run format:check

  deploy:
    name: Trigger deployment
    needs: 
      - composer-lint
      - composer-test
      - npm-format-check
      - npm-lint-check
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    uses: ./.github/workflows/deploy.yml
    secrets: inherit
